//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Firmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Firmalar()
        {
            this.tbl_Cagri = new HashSet<tbl_Cagri>();
        }
    
        public int ID_FIRMA { get; set; }
        public string FIRMA_ADI { get; set; }
        public string FIRMA_YETKILI { get; set; }
        public string FIRMA_TELEFON { get; set; }
        public string FIRMA_MAIL { get; set; }
        public string FIRMA_SEKTOR { get; set; }
        public string FIRMA_IL { get; set; }
        public string FIRMA_ILCE { get; set; }
        public string FIRMA_ADRES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cagri> tbl_Cagri { get; set; }
    }
}
