//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CagriDetay
    {
        public int ID_CAGRI_DETAY { get; set; }
        public Nullable<int> CAGRI_ID { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Saat { get; set; }
    
        public virtual tbl_Cagri tbl_Cagri { get; set; }
    }
}
