//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Personeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Personeler()
        {
            this.tbl_Gorevler = new HashSet<tbl_Gorevler>();
            this.tbl_Gorevler1 = new HashSet<tbl_Gorevler>();
            this.tbl_Cagri = new HashSet<tbl_Cagri>();
        }
    
        public int ID_PERSONAl { get; set; }
        public string PERSONEL_ADI { get; set; }
        public string PERSONEL_SOYADI { get; set; }
        public string PERSONEL_MAIL { get; set; }
        public string PERSONEL_TELEFON { get; set; }
        public string PERSONEL_GORSEL { get; set; }
        public Nullable<int> DEPARTMAN { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string ROL { get; set; }
        public string SIFRE { get; set; }
    
        public virtual tbl_Departmanlar tbl_Departmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Gorevler> tbl_Gorevler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Gorevler> tbl_Gorevler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cagri> tbl_Cagri { get; set; }
    }
}
