//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Gorevler()
        {
            this.tbl_GorevDetaylar = new HashSet<tbl_GorevDetaylar>();
        }
    
        public int ID_GOREV { get; set; }
        public Nullable<int> GOREV_VEREN { get; set; }
        public Nullable<int> GOREV_ALAN { get; set; }
        public string GOREV_ACIKLAMA { get; set; }
        public Nullable<bool> GOREV_DURUM { get; set; }
        public Nullable<System.DateTime> GOREV_TARIH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GorevDetaylar> tbl_GorevDetaylar { get; set; }
        public virtual tbl_Personeler tbl_Personeler { get; set; }
        public virtual tbl_Personeler tbl_Personeler1 { get; set; }
    }
}
