//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mesajlar
    {
        public int ID_MESAJ { get; set; }
        public int GONDEREN { get; set; }
        public int ALICI { get; set; }
        public string KONU { get; set; }
        public string MESAJ { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual tbl_Firmalar tbl_Firmalar { get; set; }
        public virtual tbl_Firmalar tbl_Firmalar1 { get; set; }
    }
}
