//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GorevDetaylar
    {
        public int ID_GOREV_DETAY { get; set; }
        public int GOREV { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SAAT { get; set; }
    
        public virtual tbl_Gorevler tbl_Gorevler { get; set; }
    }
}
